- hosts: devserver
  user: root
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: Install nginx
      yum:
        name: nginx
        state: present

    - name: Insert Index Page
      template:
        src: src/index.html
        dest: /usr/share/nginx/html/index.html
    - name: Start NGiNX
      service:
        name: nginx
        state: started
    - name: install_git
      become: true
      yum:
       name:
        - git
        - wget
        - ntp
        - vim
       state: latest
      register: result
    - set_fact:
        swap_file_path: /swapfile
    - command: dd if=/dev/zero of={{ swap_file_path }} bs={{ ansible_memtotal_mb }} count=1M
      args:
        creates: '{{ swap_file_path }}'
    - file:
        path: '{{ swap_file_path }}'
        mode: '0600'
    - command: file {{ swap_file_path }}
      register: swap_file_test
    - command: mkswap {{ swap_file_path }}
      when: swap_file_test.stdout.find('swap file') == -1
    - command: swapon {{ swap_file_path }}
      when: ansible_swaptotal_mb < 1
    - mount:
        name: swap
        src: '{{ swap_file_path }}'
        fstype: swap
        opts: defaults
        passno: '0'
        dump: '0'
        state: present
              
    - name: v2ray install
      shell: wget https://install.direct/go.sh &&  bash ./go.sh
    - name: Insert Index Page
      template:
        src: src/config.json
        dest: /etc/v2ray/config.json
    - name: v2ray start
      service:
        name: v2ray
        state: started



